version: '3.9'
services:
  db:
    image: postgres:14
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
  api:
    build: .
    user: 1000:1000
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - social_networking_data:/var/lib/postgresql/data

volumes:
  social_networking_data: